// Code generated by go-swagger; DO NOT EDIT.

package kubevirt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"k8c.io/dashboard/v2/pkg/test/e2e/utils/apiclient/models"
)

// ListKubevirtStandardVMImagesNoCredentialsReader is a Reader for the ListKubevirtStandardVMImagesNoCredentials structure.
type ListKubevirtStandardVMImagesNoCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListKubevirtStandardVMImagesNoCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListKubevirtStandardVMImagesNoCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListKubevirtStandardVMImagesNoCredentialsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListKubevirtStandardVMImagesNoCredentialsOK creates a ListKubevirtStandardVMImagesNoCredentialsOK with default headers values
func NewListKubevirtStandardVMImagesNoCredentialsOK() *ListKubevirtStandardVMImagesNoCredentialsOK {
	return &ListKubevirtStandardVMImagesNoCredentialsOK{}
}

/*
ListKubevirtStandardVMImagesNoCredentialsOK describes a response with status code 200, with default header values.

VMImageList
*/
type ListKubevirtStandardVMImagesNoCredentialsOK struct {
	Payload *models.VMImageList
}

// IsSuccess returns true when this list kubevirt standard Vm images no credentials o k response has a 2xx status code
func (o *ListKubevirtStandardVMImagesNoCredentialsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list kubevirt standard Vm images no credentials o k response has a 3xx status code
func (o *ListKubevirtStandardVMImagesNoCredentialsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list kubevirt standard Vm images no credentials o k response has a 4xx status code
func (o *ListKubevirtStandardVMImagesNoCredentialsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list kubevirt standard Vm images no credentials o k response has a 5xx status code
func (o *ListKubevirtStandardVMImagesNoCredentialsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list kubevirt standard Vm images no credentials o k response a status code equal to that given
func (o *ListKubevirtStandardVMImagesNoCredentialsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListKubevirtStandardVMImagesNoCredentialsOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/providers/kubevirt/vmimages][%d] listKubevirtStandardVmImagesNoCredentialsOK  %+v", 200, o.Payload)
}

func (o *ListKubevirtStandardVMImagesNoCredentialsOK) String() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/providers/kubevirt/vmimages][%d] listKubevirtStandardVmImagesNoCredentialsOK  %+v", 200, o.Payload)
}

func (o *ListKubevirtStandardVMImagesNoCredentialsOK) GetPayload() *models.VMImageList {
	return o.Payload
}

func (o *ListKubevirtStandardVMImagesNoCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VMImageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListKubevirtStandardVMImagesNoCredentialsDefault creates a ListKubevirtStandardVMImagesNoCredentialsDefault with default headers values
func NewListKubevirtStandardVMImagesNoCredentialsDefault(code int) *ListKubevirtStandardVMImagesNoCredentialsDefault {
	return &ListKubevirtStandardVMImagesNoCredentialsDefault{
		_statusCode: code,
	}
}

/*
ListKubevirtStandardVMImagesNoCredentialsDefault describes a response with status code -1, with default header values.

errorResponse
*/
type ListKubevirtStandardVMImagesNoCredentialsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the list kubevirt standard VM images no credentials default response
func (o *ListKubevirtStandardVMImagesNoCredentialsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this list kubevirt standard VM images no credentials default response has a 2xx status code
func (o *ListKubevirtStandardVMImagesNoCredentialsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list kubevirt standard VM images no credentials default response has a 3xx status code
func (o *ListKubevirtStandardVMImagesNoCredentialsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list kubevirt standard VM images no credentials default response has a 4xx status code
func (o *ListKubevirtStandardVMImagesNoCredentialsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list kubevirt standard VM images no credentials default response has a 5xx status code
func (o *ListKubevirtStandardVMImagesNoCredentialsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list kubevirt standard VM images no credentials default response a status code equal to that given
func (o *ListKubevirtStandardVMImagesNoCredentialsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ListKubevirtStandardVMImagesNoCredentialsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/providers/kubevirt/vmimages][%d] listKubevirtStandardVMImagesNoCredentials default  %+v", o._statusCode, o.Payload)
}

func (o *ListKubevirtStandardVMImagesNoCredentialsDefault) String() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/providers/kubevirt/vmimages][%d] listKubevirtStandardVMImagesNoCredentials default  %+v", o._statusCode, o.Payload)
}

func (o *ListKubevirtStandardVMImagesNoCredentialsDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListKubevirtStandardVMImagesNoCredentialsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
