// Code generated by go-swagger; DO NOT EDIT.

package kubevirt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"k8c.io/dashboard/v2/pkg/test/e2e/utils/apiclient/models"
)

// ListKubevirtVMImagesReader is a Reader for the ListKubevirtVMImages structure.
type ListKubevirtVMImagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListKubevirtVMImagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListKubevirtVMImagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListKubevirtVMImagesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListKubevirtVMImagesOK creates a ListKubevirtVMImagesOK with default headers values
func NewListKubevirtVMImagesOK() *ListKubevirtVMImagesOK {
	return &ListKubevirtVMImagesOK{}
}

/*
ListKubevirtVMImagesOK describes a response with status code 200, with default header values.

VMImageList
*/
type ListKubevirtVMImagesOK struct {
	Payload *models.VMImageList
}

// IsSuccess returns true when this list kubevirt Vm images o k response has a 2xx status code
func (o *ListKubevirtVMImagesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list kubevirt Vm images o k response has a 3xx status code
func (o *ListKubevirtVMImagesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list kubevirt Vm images o k response has a 4xx status code
func (o *ListKubevirtVMImagesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list kubevirt Vm images o k response has a 5xx status code
func (o *ListKubevirtVMImagesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list kubevirt Vm images o k response a status code equal to that given
func (o *ListKubevirtVMImagesOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListKubevirtVMImagesOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/providers/kubevirt/vmimages][%d] listKubevirtVmImagesOK  %+v", 200, o.Payload)
}

func (o *ListKubevirtVMImagesOK) String() string {
	return fmt.Sprintf("[GET /api/v2/providers/kubevirt/vmimages][%d] listKubevirtVmImagesOK  %+v", 200, o.Payload)
}

func (o *ListKubevirtVMImagesOK) GetPayload() *models.VMImageList {
	return o.Payload
}

func (o *ListKubevirtVMImagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VMImageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListKubevirtVMImagesDefault creates a ListKubevirtVMImagesDefault with default headers values
func NewListKubevirtVMImagesDefault(code int) *ListKubevirtVMImagesDefault {
	return &ListKubevirtVMImagesDefault{
		_statusCode: code,
	}
}

/*
ListKubevirtVMImagesDefault describes a response with status code -1, with default header values.

errorResponse
*/
type ListKubevirtVMImagesDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the list kubevirt VM images default response
func (o *ListKubevirtVMImagesDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this list kubevirt VM images default response has a 2xx status code
func (o *ListKubevirtVMImagesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list kubevirt VM images default response has a 3xx status code
func (o *ListKubevirtVMImagesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list kubevirt VM images default response has a 4xx status code
func (o *ListKubevirtVMImagesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list kubevirt VM images default response has a 5xx status code
func (o *ListKubevirtVMImagesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list kubevirt VM images default response a status code equal to that given
func (o *ListKubevirtVMImagesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ListKubevirtVMImagesDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/providers/kubevirt/vmimages][%d] listKubevirtVMImages default  %+v", o._statusCode, o.Payload)
}

func (o *ListKubevirtVMImagesDefault) String() string {
	return fmt.Sprintf("[GET /api/v2/providers/kubevirt/vmimages][%d] listKubevirtVMImages default  %+v", o._statusCode, o.Payload)
}

func (o *ListKubevirtVMImagesDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListKubevirtVMImagesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
