// Code generated by go-swagger; DO NOT EDIT.

package kubevirt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListKubevirtStandardVMImagesNoCredentialsParams creates a new ListKubevirtStandardVMImagesNoCredentialsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListKubevirtStandardVMImagesNoCredentialsParams() *ListKubevirtStandardVMImagesNoCredentialsParams {
	return &ListKubevirtStandardVMImagesNoCredentialsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListKubevirtStandardVMImagesNoCredentialsParamsWithTimeout creates a new ListKubevirtStandardVMImagesNoCredentialsParams object
// with the ability to set a timeout on a request.
func NewListKubevirtStandardVMImagesNoCredentialsParamsWithTimeout(timeout time.Duration) *ListKubevirtStandardVMImagesNoCredentialsParams {
	return &ListKubevirtStandardVMImagesNoCredentialsParams{
		timeout: timeout,
	}
}

// NewListKubevirtStandardVMImagesNoCredentialsParamsWithContext creates a new ListKubevirtStandardVMImagesNoCredentialsParams object
// with the ability to set a context for a request.
func NewListKubevirtStandardVMImagesNoCredentialsParamsWithContext(ctx context.Context) *ListKubevirtStandardVMImagesNoCredentialsParams {
	return &ListKubevirtStandardVMImagesNoCredentialsParams{
		Context: ctx,
	}
}

// NewListKubevirtStandardVMImagesNoCredentialsParamsWithHTTPClient creates a new ListKubevirtStandardVMImagesNoCredentialsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListKubevirtStandardVMImagesNoCredentialsParamsWithHTTPClient(client *http.Client) *ListKubevirtStandardVMImagesNoCredentialsParams {
	return &ListKubevirtStandardVMImagesNoCredentialsParams{
		HTTPClient: client,
	}
}

/*
ListKubevirtStandardVMImagesNoCredentialsParams contains all the parameters to send to the API endpoint

	for the list kubevirt standard VM images no credentials operation.

	Typically these are written to a http.Request.
*/
type ListKubevirtStandardVMImagesNoCredentialsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list kubevirt standard VM images no credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListKubevirtStandardVMImagesNoCredentialsParams) WithDefaults() *ListKubevirtStandardVMImagesNoCredentialsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list kubevirt standard VM images no credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListKubevirtStandardVMImagesNoCredentialsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list kubevirt standard VM images no credentials params
func (o *ListKubevirtStandardVMImagesNoCredentialsParams) WithTimeout(timeout time.Duration) *ListKubevirtStandardVMImagesNoCredentialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list kubevirt standard VM images no credentials params
func (o *ListKubevirtStandardVMImagesNoCredentialsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list kubevirt standard VM images no credentials params
func (o *ListKubevirtStandardVMImagesNoCredentialsParams) WithContext(ctx context.Context) *ListKubevirtStandardVMImagesNoCredentialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list kubevirt standard VM images no credentials params
func (o *ListKubevirtStandardVMImagesNoCredentialsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list kubevirt standard VM images no credentials params
func (o *ListKubevirtStandardVMImagesNoCredentialsParams) WithHTTPClient(client *http.Client) *ListKubevirtStandardVMImagesNoCredentialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list kubevirt standard VM images no credentials params
func (o *ListKubevirtStandardVMImagesNoCredentialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListKubevirtStandardVMImagesNoCredentialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
