// Code generated by go-swagger; DO NOT EDIT.

package kubevirt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListKubevirtVMImagesParams creates a new ListKubevirtVMImagesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListKubevirtVMImagesParams() *ListKubevirtVMImagesParams {
	return &ListKubevirtVMImagesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListKubevirtVMImagesParamsWithTimeout creates a new ListKubevirtVMImagesParams object
// with the ability to set a timeout on a request.
func NewListKubevirtVMImagesParamsWithTimeout(timeout time.Duration) *ListKubevirtVMImagesParams {
	return &ListKubevirtVMImagesParams{
		timeout: timeout,
	}
}

// NewListKubevirtVMImagesParamsWithContext creates a new ListKubevirtVMImagesParams object
// with the ability to set a context for a request.
func NewListKubevirtVMImagesParamsWithContext(ctx context.Context) *ListKubevirtVMImagesParams {
	return &ListKubevirtVMImagesParams{
		Context: ctx,
	}
}

// NewListKubevirtVMImagesParamsWithHTTPClient creates a new ListKubevirtVMImagesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListKubevirtVMImagesParamsWithHTTPClient(client *http.Client) *ListKubevirtVMImagesParams {
	return &ListKubevirtVMImagesParams{
		HTTPClient: client,
	}
}

/*
ListKubevirtVMImagesParams contains all the parameters to send to the API endpoint

	for the list kubevirt VM images operation.

	Typically these are written to a http.Request.
*/
type ListKubevirtVMImagesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list kubevirt VM images params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListKubevirtVMImagesParams) WithDefaults() *ListKubevirtVMImagesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list kubevirt VM images params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListKubevirtVMImagesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list kubevirt VM images params
func (o *ListKubevirtVMImagesParams) WithTimeout(timeout time.Duration) *ListKubevirtVMImagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list kubevirt VM images params
func (o *ListKubevirtVMImagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list kubevirt VM images params
func (o *ListKubevirtVMImagesParams) WithContext(ctx context.Context) *ListKubevirtVMImagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list kubevirt VM images params
func (o *ListKubevirtVMImagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list kubevirt VM images params
func (o *ListKubevirtVMImagesParams) WithHTTPClient(client *http.Client) *ListKubevirtVMImagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list kubevirt VM images params
func (o *ListKubevirtVMImagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListKubevirtVMImagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
