// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImageCloning ImageCloning represents options for kubevirt disk-image cloning.
//
// swagger:model ImageCloning
type ImageCloning struct {

	// Enable allows to enable/disable the option to clone disk images (defaults to false).
	Enable bool `json:"enable,omitempty"`

	// StorageClass represents storage-class for preAllocated DataVolumes.
	StorageClass string `json:"storageClass,omitempty"`
}

// Validate validates this image cloning
func (m *ImageCloning) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this image cloning based on context it is used
func (m *ImageCloning) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImageCloning) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageCloning) UnmarshalBinary(b []byte) error {
	var res ImageCloning
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
